export const TIMEZONES = [
  { value: 'Pacific/Midway', label: '(UTC-11:00) Midway Island, Samoa' },
  { value: 'America/Adak', label: '(UTC-10:00) Hawaii-Aleutian' },
  { value: 'Etc/GMT+10', label: '(UTC-10:00) Hawaii' },
  { value: 'Pacific/Marquesas', label: '(UTC-09:30) Marquesas Islands' },
  { value: 'Pacific/Gambier', label: '(UTC-09:00) Gambier Islands' },
  { value: 'America/Anchorage', label: '(UTC-09:00) Alaska' },
  { value: 'America/Ensenada', label: '(UTC-08:00) Tijuana, Baja California' },
  { value: 'Etc/GMT+8', label: '(UTC-08:00) Pitcairn Islands' },
  { value: 'America/Los_Angeles', label: '(UTC-08:00) Pacific Time (US & Canada)' },
  { value: 'America/Denver', label: '(UTC-07:00) Mountain Time (US & Canada)' },
  { value: 'America/Chihuahua', label: '(UTC-07:00) Chihuahua, La Paz, Mazatlan' },
  { value: 'America/Dawson_Creek', label: '(UTC-07:00) Arizona' },
  { value: 'America/Belize', label: '(UTC-06:00) Saskatchewan, Central America' },
  { value: 'America/Cancun', label: '(UTC-06:00) Guadalajara, Mexico City, Monterrey' },
  { value: 'America/Chicago', label: '(UTC-06:00) Central Time (US & Canada)' },
  { value: 'America/Chile/EasterIsland', label: '(UTC-06:00) Easter Island' },
  { value: 'America/Bogota', label: '(UTC-05:00) Bogota, Lima, Quito, Rio Branco' },
  { value: 'America/New_York', label: '(UTC-05:00) Eastern Time (US & Canada)' },
  { value: 'America/Havana', label: '(UTC-05:00) Cuba' },
  { value: 'America/Caracas', label: '(UTC-04:30) Caracas' },
  { value: 'America/Campo_Grande', label: '(UTC-04:00) Amazon Time (Brazil)' },
  { value: 'America/Goyane', label: '(UTC-04:00) Atlantic Time (Goiania)' },
  { value: 'America/Asuncion', label: '(UTC-04:00) Asuncion' },
  { value: 'America/Halifax', label: '(UTC-04:00) Atlantic Time (Canada)' },
  { value: 'America/Cuiaba', label: '(UTC-04:00) Cuiaba' },
  { value: 'America/La_Paz', label: '(UTC-04:00) La Paz' },
  { value: 'America/Santiago', label: '(UTC-04:00) Santiago' },
  { value: 'America/St_Johns', label: '(UTC-03:30) Newfoundland' },
  { value: 'America/Araguaina', label: '(UTC-03:00) Araguaina' },
  { value: 'America/Argentine/Buenos_Aires', label: '(UTC-03:00) Buenos Aires, Georgetown' },
  { value: 'America/Cayenne', label: '(UTC-03:00) Cayenne, Fortaleza' },
  { value: 'America/Sao_Paulo', label: '(UTC-03:00) Brasilia' },
  { value: 'America/Miquelon', label: '(UTC-03:00) Saint Pierre and Miquelon' },
  { value: 'America/Montevideo', label: '(UTC-03:00) Montevideo' },
  { value: 'America/Bahia', label: '(UTC-03:00) Salvador' },
  { value: 'America/Noronha', label: '(UTC-02:00) Fernando de Noronha' },
  { value: 'Atlantic/Azores', label: '(UTC-01:00) Azores' },
  { value: 'Atlantic/Cape_Verde', label: '(UTC-01:00) Cape Verde Is.' },
  { value: 'Africa/Casablanca', label: '(UTC+00:00) Casablanca, Monrovia, Reykjavik' },
  { value: 'Etc/GMT', label: '(UTC+00:00) Dublin, Edinburgh, Lisbon, London' },
  { value: 'Europe/Amsterdam', label: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna' },
  { value: 'Europe/Belgrade', label: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague' },
  { value: 'Europe/Brussels', label: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris' },
  { value: 'Europe/Sarajevo', label: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb' },
  { value: 'Africa/Lagos', label: '(UTC+01:00) West Central Africa' },
  { value: 'Europe/Tirane', label: '(UTC+01:00) Tirane (CET)' },
  { value: 'Europe/Athens', label: '(UTC+02:00) Athens, Bucharest, Istanbul' },
  { value: 'Europe/Helsinki', label: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius' },
  { value: 'Europe/Prishtina', label: '(UTC+02:00) Prishtina (EET)' },
  { value: 'Africa/Cairo', label: '(UTC+02:00) Cairo' },
  { value: 'Africa/Harare', label: '(UTC+02:00) Harare, Pretoria' },
  { value: 'Europe/Kaliningrad', label: '(UTC+02:00) Kaliningrad, South Africa' },
  { value: 'Asia/Amman', label: '(UTC+02:00) Amman' },
  { value: 'Asia/Beirut', label: '(UTC+02:00) Beirut' },
  { value: 'Asia/Jerusalem', label: '(UTC+02:00) Jerusalem' },
  { value: 'Asia/Gaza', label: '(UTC+02:00) Gaza' },
  { value: 'Africa/Windhoek', label: '(UTC+02:00) Windhoek' },
  { value: 'Asia/Baghdad', label: '(UTC+03:00) Baghdad' },
  { value: 'Asia/Kuwait', label: '(UTC+03:00) Kuwait, Riyadh' },
  { value: 'Europe/Moscow', label: '(UTC+03:00) Moscow, St. Petersburg, Volgograd' },
  { value: 'Africa/Nairobi', label: '(UTC+03:00) Nairobi' },
  { value: 'Asia/Tbilisi', label: '(UTC+04:00) Tbilisi' },
  { value: 'Asia/Yerevan', label: '(UTC+04:00) Yerevan' },
  { value: 'Asia/Dubai', label: '(UTC+04:00) Abu Dhabi, Muscat' },
  { value: 'Asia/Baku', label: '(UTC+04:00) Baku' },
  { value: 'Asia/Port_Louis', label: '(UTC+04:00) Port Louis' },
  { value: 'Asia/Tehran', label: '(UTC+03:30) Tehran' },
  { value: 'Asia/Kabul', label: '(UTC+04:30) Kabul' },
  { value: 'Asia/Yekaterinburg', label: '(UTC+05:00) Ekaterinburg' },
  { value: 'Asia/Karachi', label: '(UTC+05:00) Islamabad, Karachi, Tashkent' },
  { value: 'Asia/Calcutta', label: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi' },
  { value: 'Asia/Colombo', label: '(UTC+05:30) Sri Jayawardenepura' },
  { value: 'Asia/Katmandu', label: '(UTC+05:45) Kathmandu' },
  { value: 'Asia/Almaty', label: '(UTC+06:00) Almaty, Novosibirsk' },
  { value: 'Asia/Dhaka', label: '(UTC+06:00) Astana, Dhaka' },
  { value: 'Asia/Rangoon', label: '(UTC+06:30) Yangon (Rangoon)' },
  { value: 'Asia/Bangkok', label: '(UTC+07:00) Bangkok, Hanoi, Jakarta' },
  { value: 'Asia/Krasnoyarsk', label: '(UTC+07:00) Krasnoyarsk' },
  { value: 'Asia/Hong_Kong', label: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi' },
  { value: 'Asia/Kuala_Lumpur', label: '(UTC+08:00) Kuala Lumpur, Singapore' },
  { value: 'Asia/Irkutsk', label: '(UTC+08:00) Irkutsk, Ulaan Bataar' },
  { value: 'Australia/Perth', label: '(UTC+08:00) Perth' },
  { value: 'Asia/Taipei', label: '(UTC+08:00) Taipei' },
  { value: 'Asia/Tokyo', label: '(UTC+09:00) Osaka, Sapporo, Tokyo' },
  { value: 'Asia/Seoul', label: '(UTC+09:00) Seoul' },
  { value: 'Asia/Yakutsk', label: '(UTC+09:00) Yakutsk' },
  { value: 'Australia/Adelaide', label: '(UTC+09:30) Adelaide' },
  { value: 'Australia/Darwin', label: '(UTC+09:30) Darwin' },
  { value: 'Australia/Brisbane', label: '(UTC+10:00) Brisbane' },
  { value: 'Australia/Canberra', label: '(UTC+10:00) Canberra, Melbourne, Sydney' },
  { value: 'Australia/Hobart', label: '(UTC+10:00) Hobart' },
  { value: 'Pacific/Guam', label: '(UTC+10:00) Guam, Port Moresby' },
  { value: 'Asia/Vladivostok', label: '(UTC+10:00) Vladivostok' },
  { value: 'Asia/Magadan', label: '(UTC+11:00) Magadan, Solomon Is., New Caledonia' },
  { value: 'Pacific/Auckland', label: '(UTC+12:00) Auckland, Wellington' },
  { value: 'Pacific/Fiji', label: '(UTC+12:00) Fiji, Kamchatka, Marshall Is.' },
  { value: 'Pacific/Tongatapu', label: '(UTC+13:00) Nuku\'alofa' }
];
