export interface RealtimeEventEnvelope {
  eventId: string;
  type: string;
  entity: string;
  entityId: string | null;
  scopeType: 'company';
  scopeId: string;
  version: number | null;
  occurredAt: string;
  actorUserId: string | null;
  payload: unknown;
}

export const RealtimeEventType = {
  // Sites
  COMPANY_SITE_CREATED: 'COMPANY_SITE_CREATED',
  COMPANY_SITE_UPDATED: 'COMPANY_SITE_UPDATED',
  COMPANY_SITE_ACTIVATED: 'COMPANY_SITE_ACTIVATED',
  COMPANY_SITE_DISABLED: 'COMPANY_SITE_DISABLED',
  // Departments
  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',
  DEPARTMENT_DELETED: 'DEPARTMENT_DELETED',
  // Employees
  EMPLOYEE_PROVISIONED: 'EMPLOYEE_PROVISIONED',
  // Announcements
  ANNOUNCEMENT_CREATED: 'ANNOUNCEMENT_CREATED',
  ANNOUNCEMENT_DELETED: 'ANNOUNCEMENT_DELETED',
  // Leave
  LEAVE_REQUEST_SUBMITTED: 'LEAVE_REQUEST_SUBMITTED',
  LEAVE_REQUEST_APPROVED: 'LEAVE_REQUEST_APPROVED',
  LEAVE_REQUEST_REJECTED: 'LEAVE_REQUEST_REJECTED',
  // Attendance
  ATTENDANCE_MANUAL_CHECK_IN: 'ATTENDANCE_MANUAL_CHECK_IN',
  ATTENDANCE_MANUAL_CHECK_OUT: 'ATTENDANCE_MANUAL_CHECK_OUT',
  ATTENDANCE_EVENT_REVIEWED: 'ATTENDANCE_EVENT_REVIEWED',
  ATTENDANCE_DAY_ADJUSTED: 'ATTENDANCE_DAY_ADJUSTED',
  // Settings
  COMPANY_SETTINGS_UPDATED: 'COMPANY_SETTINGS_UPDATED',
} as const;

export type RealtimeEventTypeKey = keyof typeof RealtimeEventType;
